apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
            - ./infra/k8s-dev/*
build:
    local:
        push: false
    artifacts:
        - image: rahulvyas/auth
          context: auth
          docker:
            dockerfile: dockerfile
          sync:
            manual:
                - src: './src/**/*.ts'
                  dest: .
